### ISSUE TITLE
local support modules should be either absorbed or moved into a package

### ISSUE THREAD

**Issue by yarikoptic** [CONP-PCNO/git-annex-remote-globus#5]
currently code relies on ambiguous (looks global but is local)  imports:

```python
from lookup_url import lookup_url
...
from globusclient import GlobusClient
from annexremote import Master
from annexremote import ExportRemote
from annexremote import SpecialRemote
from annexremote import RemoteError, ProtocolError
```

those files cannot be deployed (installed) on their own, so either would need to be moved into some local "proper package" (e.g. `git_annex_remote_globus` ;) ) or  just absorbed within `git-annex-remote-globus` .  In the former case, even the `git-annex-remote-globus` code could pretty much be moved into the package (e.g. as `git_annex_remote_globus/cmd.py`) and the actual `git_annex_remote_globus` would be just having the `__main__` portion.
That would make it easier to (eventually) establish `git_annex_remote_globus/tests` which would test functionality within that cmd.py somehow

**Comment by yarikoptic** [comment]
and that is why it is simply not usable with python3 without adjusting PYTHONPATH (actually doesn't even if I adjust PYTHONPATH to point to that directory)
```
(git-annex)lena:~datalad/trash/testds-urls[master]git-annex
$> git annex initremote globus type=external externaltype=globus encryption=none
initremote globus Traceback (most recent call last):
  File "/home/yoh/proj/datalad/GLOBUSannex/git-annex-remote-globus", line 17, in <module>
    from annexremote import Master
ModuleNotFoundError: No module named 'annexremote'
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/GLOBUSannex/git-annex-remote-globus", line 17, in <module>
    from annexremote import Master
ModuleNotFoundError: No module named 'annexremote'

git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
failed
git-annex: initremote: 1 failed
```
